builder/src/Gren/Outline.hs, builder/src/Reporting/Exit.hs, terminal/src/Init.hs
For Gren 0.2.0, the `gren-lang/json` package is merged into `gren-lang/core`. The required dependency on `gren-lang/json` in packages can thus be removed.
=> Change default application dependencies

builder/src/Deps/Package.hs, builder/src/Deps/Solver.hs, builder/src/Directories.hs, builder/src/Git.hs, builder/src/Gren/Details.hs, builder/src/Reporting/Exit.hs, compiler/src/Gren/Constraint.hs, gren.cabal, terminal/src/Bump.hs, terminal/src/Diff.hs, terminal/src/Init.hs, terminal/src/Install.hs, terminal/src/Publish.hs, terminal/src/Repl.hs
Compiling example-projects with cold cache:
without this pr: 45 seconds
with this pr: 13 seconds
=> Package manager improvements

builder/src/Build.hs, builder/src/Gren/Details.hs, builder/src/Gren/Platform.hs, builder/src/Reporting/Exit.hs, compiler/src/AST/Optimized.hs, compiler/src/Compile.hs, compiler/src/Generate/JavaScript.hs, compiler/src/Generate/JavaScript/Expression.hs, compiler/src/Generate/Node.hs, compiler/src/Optimize/Module.hs, compiler/src/Reporting/Error/Main.hs, gren.cabal, terminal/src/Diff.hs, terminal/src/Make.hs, terminal/src/Publish.hs
This adds support for compiling applications that target the `node` platform.
It adds a couple of changes:
1. When the platform is `node`, `main` functions can have a `String` signature.
2. When leaving off the extension of a filename, it generates a file with a shebang line, so that the file can be executed directly on unix systems.
3. You can now import a compiled `.js` file into Node, and it will contain a Gren property with all exported main functions.
4. Error messages have been updated accordingly.
`String` returning main functions works as expected. Full programs probably don't, but it's hard to test this until we have a more advanced platform package.
=> Add support for compiling NodeJS applications

builder/src/Build.hs, compiler/src/AST/Source.hs, compiler/src/Canonicalize/Effects.hs, compiler/src/Canonicalize/Environment/Local.hs, compiler/src/Canonicalize/Module.hs, compiler/src/Gren/Format.hs, compiler/src/Gren/Format/Normalize.hs, compiler/src/Parse/Module.hs, compiler/src/Parse/Primitives.hs, compiler/src/Text/PrettyPrint/Avh4/Block.hs, compiler/src/Text/PrettyPrint/Avh4/Indent.hs, gren.cabal, terminal/src/Format.hs, terminal/src/Main.hs
This is the base formatting logic.  This is one part of https://github.com/gren-lang/compiler/issues/42.  Handling non-documentation comments and linebreak sensitivity are not part of this PR.
Run with `gren format` from inside a project with a `gren.json`, or run `gren format <files and/or directories...>`.
This is based on the learnings from elm-format, but is rewritten and greatly simplified, and also should be more performant.
TODO:
Will be done in a future PR (tracked in https://github.com/gren-lang/compiler/issues/42):
- allow kernel module features when formatting
=> Implement formatting logic (without comments/linebreak support)

compiler/src/Gren/Format.hs
https://github.com/gren-lang/compiler/pull/121 and https://github.com/gren-lang/compiler/pull/117 both just got merged, but they conflict with each other.
This should fix it.
=> Fix merge conflict with https://github.com/gren-lang/compiler/pull/121

gren.cabal, terminal/src/Docs.hs, terminal/src/Main.hs, terminal/src/Make.hs
Creating a json file with a project's documentation is now a seperate command. This also allows for outputting the documentation to stdout instead of to a file, which can simplify external tools.
=> Create a new docs command, and remove the --docs flag from make.

builder/src/Deps/Solver.hs, builder/src/Gren/Details.hs, builder/src/Gren/Outline.hs, builder/src/Reporting/Exit.hs, gren.cabal, terminal/impl/Terminal.hs, terminal/impl/Terminal/Error.hs, terminal/impl/Terminal/Internal.hs, terminal/src/Init.hs, terminal/src/Install.hs, terminal/src/Main.hs, terminal/src/Package.hs, terminal/src/Validate.hs
Package commands like `diff`, `bump`, `install`, are moved to a package prefix.
This means that where you earlier could write `gren diff`, you now need to write `gren package diff`.
Other changes:
* You can now run `install` without any arguments. This will download all dependencies for your project.
* `publish` is now `validate`, and doesn't fail if running on a published version, as long as the code is the same as the published version.
Also changed a bunch of error message content.
=> Add package prefix to CLI interface, and move package commands there

terminal/src/Repl.hs
Entering statements in the repl would cause it to crash, as it used the empty tuple as a default return value. Tuples were removed before the 0.1.0 release.
Also made a change so that dependencies are downloaded before repl initialization.
Fixes #127
=> Fix repl crash when entering statements

builder/src/Build.hs, builder/src/Gren/Details.hs, compiler/src/AST/Source.hs, compiler/src/AST/SourceComments.hs, compiler/src/Canonicalize/Effects.hs, compiler/src/Canonicalize/Environment/Local.hs, compiler/src/Canonicalize/Expression.hs, compiler/src/Canonicalize/Module.hs, compiler/src/Gren/Format.hs, compiler/src/Parse/Expression.hs, compiler/src/Parse/Module.hs, compiler/src/Reporting/Error/Syntax.hs, compiler/src/Reporting/Render/Type/Localizer.hs, gren.cabal, terminal/src/Format.hs, tests/Integration/FormatSpec.hs
This is an incremental part of the retain comments task of https://github.com/gren-lang/compiler/issues/42.  More locations of comments will be retained in future PRs (those remaining locations are being tracked by compiler warnings).
This implements comment handling in the following places:
- before the `module` line
- `module 💬 Name 💬 exposing 💬 (..) 💬`
- between `module` line and module doc comments
- between module doc comments and `import`s
- `(💬 expression)`
This also sets up a pattern for testing formatting behavior.
=> Formatting retains comments (module header and paren expressions)

compiler/src/Gren/Format/Normalize.hs, terminal/src/Format.hs
Only remove default imports if we're not formatting `gren-lang/core`.
Tagging for review: @avh4
=> Keep default imports for core

builder/src/Gren/Outline.hs, builder/src/Reporting/Exit.hs, builder/src/Reporting/Exit/Help.hs, compiler/src/Data/NonEmptyList.hs, terminal/src/Format.hs, tests/Integration/FormatSpec.hs
This resolves some TODOs in gren format where parse errors would lead to an impure exception.
I had to make some design decisions that I'm happy to discuss:
- If you try to format more than one file, you will get exit code 0, and no parse error message, even if all the files had parse errors.
- If you format a single file that has a parse error, this will be reported.
My reasoning is that when you format a single file you are more likely to be interested in why formatting failed, whereas when formatting a project and you might be happy knowing which files were successfully formatted.
If that made sense we might possibly also want to differentiate between formatting a project with a single file, and formatting a single file from the command line.
When validating it will currently report …
=> Report errors in gren format

compiler/src/Gren/Docs.hs
Top level arrays are technically not valid JSON.
Also, every item in the docs output is unique by its module name, so it makes sense to use that as key.
There are improvements that could be made, like removing the `name:` key from each module object, and encode values, binops, etc. in the same way. Postponing such work for later.
Fixes #134
=> `gren docs` should output an object, not an array

compiler/src/Data/Name.hs, compiler/src/Generate/JavaScript/Expression.hs
This optimization is sensitive to the namespace of those two functions, which moved to a `Math` module in Gren 0.1.
=> Fix regression where truncate and remainderBy wasn't inlined

builder/src/Build.hs, builder/src/Gren/Details.hs, compiler/src/AST/Source.hs, compiler/src/Canonicalize/Environment/Local.hs, compiler/src/Canonicalize/Expression.hs, compiler/src/Canonicalize/Module.hs, compiler/src/Canonicalize/Type.hs, compiler/src/Gren/Compiler/Type.hs, compiler/src/Gren/Format.hs, compiler/src/Gren/Format/Normalize.hs, compiler/src/Gren/Kernel.hs, compiler/src/Parse/Declaration.hs, compiler/src/Parse/Expression.hs, compiler/src/Parse/Module.hs, compiler/src/Parse/Type.hs, compiler/src/Reporting/Render/Type.hs, compiler/src/Reporting/Render/Type/Localizer.hs, terminal/src/Repl.hs, tests/Helpers/Parse.hs, tests/Integration/FormatSpec.hs, tests/Parse/AliasSpec.hs, tests/Parse/RecordUpdateSpec.hs
As a side note, to capture the comments _after_ a sequence of items that are parsed with a recursive function, the comments _between_ elements were temporarily captured.  In those cases, I went ahead and attached those "between" comments to the AST, even though they aren't output yet.  This happened for `import` statements, `case` branches, type arguments, and custom type variants.
=> format: retain top-level comments

builder/src/Build.hs, compiler/src/AST/Source.hs, compiler/src/AST/SourceComments.hs, compiler/src/Canonicalize/Effects.hs, compiler/src/Canonicalize/Environment/Local.hs, compiler/src/Canonicalize/Expression.hs, compiler/src/Canonicalize/Module.hs, compiler/src/Gren/Format.hs, compiler/src/Gren/Format/Normalize.hs, compiler/src/Parse/Declaration.hs, compiler/src/Parse/Expression.hs, compiler/src/Parse/Module.hs, compiler/src/Parse/Space.hs, compiler/src/Reporting/Annotation.hs, terminal/src/Repl.hs, tests/Integration/FormatSpec.hs, tests/Parse/SpaceSpec.hs
After this PR, https://github.com/gren-lang/example-projects can now be safely formatted! (At least the `main` branch; I'll check `0.2` branch next)
- retain comments within top-level value declarations...
- retain comments within `let` expressions...
- retain comments within lambda expressions...
=> format: retain comments in expression bodies (value decls, let, lambda)

compiler/src/AST/Source.hs, compiler/src/AST/SourceComments.hs, compiler/src/Canonicalize/Expression.hs, compiler/src/Canonicalize/Pattern.hs, compiler/src/Gren/Format.hs, compiler/src/Parse/Declaration.hs, compiler/src/Parse/Expression.hs, compiler/src/Parse/Module.hs, compiler/src/Parse/Pattern.hs, compiler/src/Parse/Space.hs, compiler/src/Reporting/Annotation.hs, tests/Integration/FormatSpec.hs, tests/Parse/MultilineStringSpec.hs, tests/Parse/UnderscorePatternSpec.hs
- retain comments in `case` expressions:
- for each branch:
- retain comments in `if` expressions:
- for each "if/then" clause:
=> format: retain comments in `case` and `if` expressions

compiler/src/AST/Source.hs, compiler/src/AST/SourceComments.hs, compiler/src/Canonicalize/Environment/Dups.hs, compiler/src/Canonicalize/Environment/Local.hs, compiler/src/Canonicalize/Expression.hs, compiler/src/Canonicalize/Pattern.hs, compiler/src/Canonicalize/Type.hs, compiler/src/Gren/Compiler/Type.hs, compiler/src/Gren/Format.hs, compiler/src/Parse/Expression.hs, compiler/src/Parse/Pattern.hs, compiler/src/Parse/Type.hs, compiler/src/Reporting/Render/Type.hs, tests/Integration/FormatSpec.hs, tests/Parse/RecordUpdateSpec.hs
- retain comments in array expressions
- (not included in this PR: in an empty array)
- retain comments in array patterns
- (not included in this PR: in an empty array pattern)
- retain comments in record expressions
- (not included in this PR: in an empty record)
- retain comments in record types
- (not included in this PR: in an empty record type)
- (not included in this PR: retain comments in record patterns)
=> format: retain comments in arrays and records

compiler/src/AST/Source.hs, compiler/src/AST/SourceComments.hs, compiler/src/Canonicalize/Expression.hs, compiler/src/Canonicalize/Module.hs, compiler/src/Gren/Format.hs, compiler/src/Parse/Declaration.hs, compiler/src/Parse/Expression.hs, tests/Integration/FormatSpec.hs
=> format: retain comments in remaining expressions

compiler/src/AST/Source.hs, compiler/src/AST/SourceComments.hs, compiler/src/Canonicalize/Environment/Local.hs, compiler/src/Canonicalize/Type.hs, compiler/src/Gren/Compiler/Type.hs, compiler/src/Gren/Format.hs, compiler/src/Parse/Declaration.hs, compiler/src/Parse/Module.hs, compiler/src/Parse/Type.hs, compiler/src/Reporting/Render/Type.hs, terminal/src/Repl.hs, tests/Integration/FormatSpec.hs
- retain comments in type parentheses
- retain comments in function types
- retain comments in union type declarations
=> format: retain comments in remaining types

builder/src/Deps/Package.hs, builder/src/Deps/Solver.hs, builder/src/Git.hs, builder/src/Gren/Details.hs, terminal/src/Docs.hs, terminal/src/Init.hs, terminal/src/Make.hs, terminal/src/Package/Install.hs, terminal/src/Package/Uninstall.hs, terminal/src/Repl.hs
When compiling docs or source code with the `--output=/dev/stdout` flag, corrupted data would be the result due to some unfortunate `putStrLn`'s.
This should now be fixed.
=> Fix stdout output when compiling docs

compiler/src/Gren/Format.hs, compiler/src/Parse/Module.hs, tests/Integration/FormatSpec.hs
Fixes a bug noted in Zulip, where `infix` top-level declarations would get reversed when formatted.  (Only applicable to kernel packages like `core`, since infix operator declarations aren't allowed elsewhere.)
=> format: (kernel modules) keep infix operators in the original order

compiler/src/AST/Source.hs, compiler/src/Canonicalize/Expression.hs, compiler/src/Canonicalize/Module.hs, compiler/src/Canonicalize/Pattern.hs, compiler/src/Data/Utf8.hs, compiler/src/Gren/Format.hs, compiler/src/Gren/Int.hs, compiler/src/Gren/String.hs, compiler/src/Parse/Declaration.hs, compiler/src/Parse/Expression.hs, compiler/src/Parse/Module.hs, compiler/src/Parse/Number.hs, compiler/src/Parse/Pattern.hs, compiler/src/Parse/String.hs, gren.cabal, tests/Integration/FormatSpec.hs
A few various things that seem good to fix before the 0.2 release:
=> format: good things to fix before 0.2

.gitignore, builder/src/Reporting/Exit.hs, terminal/src/Make.hs
Fix #93
This is an almost complete solution apart from the problem described in #172, which leads to a `Success!` message being printed before an error message is shown, which should be fixed in a different PR.
=> Forbid make output for package type projects

builder/src/Gren/Details.hs, builder/src/Gren/PossibleFilePath.hs, terminal/src/Package/Install.hs, terminal/src/Package/Uninstall.hs
If the project being compiled requires a local dependency, then ignore the cache to make sure the latest changes are compiled. This also disables writing a cache for the dependency in question.
This will always cold compile the local dependency (but fortunetly, other dependencies are still cached). Improvements in this area is left for a future PR.
=> No caching for local deps

builder/src/Git.hs, builder/src/Gren/Details.hs, gren.cabal
When compiling a `gren-lang` package, extract the git commit signature from the last commit which modified a js file, and make sure the public key matches the public key of Gren's BDFL.
Required to make sure that local dependencies aren't being used to avoid the restrictions on kernel code.
=> Verify kernel code packages

compiler/src/Data/Utf8.hs, compiler/src/Gren/Format.hs, tests/Integration/FormatSpec.hs
Fixes https://github.com/gren-lang/compiler/issues/191
This is a little bit tricky because the AST contains the string values in a format that is optimized for outputting the compiled javascript (it is a fully-assembled `ByteArray#` in UTF8 encoding, with javascript escape sequences, also with unicode escapes normalized to use only 4-digit hex codes).  Perhaps a more ideal option would be to refactor the parser and AST to retain the `String.Chunk`s that are currently used internally in `Gren.String`, but that seemed complicated to do.  So instead this PR just has the formatter try to re-parse the string to recover the information needed to format it properly.
(elm-format hasn't had to deal with this yet, since it is still based on an older version of Elm's parser, so the AST there …
=> format: Fix unicode escapes in string literals

builder/src/Git.hs, builder/src/Gren/Details.hs, builder/src/Reporting/Exit.hs
Improve the error message displayed to the user when a dependency is found to have unsigned kernel code, or kernel code signed with the wrong public key.
Also prevent the compiler from crashing when a commit touching .js files is completely unsigned.
Fixes #189
=> Improve error message for kernel pkg with unsigned commit

builder/src/Gren/Details.hs
If you were referencing a local dependency which has a version in its `gren.json` that is present in the package cache, the package cache is being read and _not_ the local dependency.
This PR simply ignores the package cache if the package is a local dependency.
Fixes #186
=> Ignore package cache when verifying local dependency.

compiler/src/Gren/Format.hs, gren.cabal, tests/Integration/FormatSpec.hs
I published prettyprint-avh4 0.1.1.0 with a bug fix (end-of-line comments are now correctly joined to the preceeding line in some cases where they weren't before) and some added helper functions.  https://hackage.haskell.org/package/prettyprint-avh4-0.1.1.0/changelog
This upgrades to the new version.
=> Upgrade prettyprint

docs/kernel_code.md
Documenting the gotcha you pointed out here: https://github.com/blaix/gren-lang-node/pull/1#discussion_r1223534170
=> Add docs for kernel object properties and optimize

compiler/src/Reporting/Doc.hs, terminal/impl/Terminal/Error.hs
https://github.com/gren-lang/compiler/issues/207
=> Disable ansi printing when NO_COLOR is set

compiler/src/Reporting/Doc.hs
Hint links points directly to GitHub file
Previously, hint links were pointing to https://gren-lang.org/0.3.0/imports, which leads to 404. 
Now it points directly to https://github.com/gren-lang/compiler/blob/0.3.0/hints/imports.md
=> fix: hint links

CONTRIBUTING.md
**TL;DR:** Match the doc repo in [replacing Zulip with Discord](https://github.com/gren-lang/gren-lang.github.io/commit/28aa4876942d0ccfe903e7d8567b33e9046c4ab6)
* Move Zulip to the bottom of the file as a historic location
* Add Discord Join instructions with links to channels
* Add cross-reference to Discord's limited forum channel documentation
* Various phrasing tweaks
=> Replace Zulip in CONTRIBUTING.md with Discord

CONTRIBUTORS, hints/port-modules.md, terminal/src/Main.hs
**TL;DR:** Fix some links I found in help text while causing errors locally :sweat_smile:
* Replace Zulip with Discord in hints/port-modules.md
* Replace Zulip with Discord in terminal/src/Main.hs
* Homogenize line length in terminal/src/Main.hs help nudge text
=> Replace help text Zulip references with Discord

compiler/src/Generate/SourceMap.hs
Ahh, the infamous off-by-one-error 🤦
=> Make sure to include last line of source mappings.

CONTRIBUTORS, compiler/src/Parse/String.hs, compiler/src/Reporting/Error/Syntax.hs, tests/Parse/MultilineStringSpec.hs
This should fix #254.
I also fixed another bug while I was at it. Gren was silently dropping the last newline if the string didn't end with a newline.
=> Allow CRLF at the start of multiline strings

compiler/src/Parse/String.hs, tests/Parse/MultilineStringSpec.hs
=> Make single quotes and escapes no longer eat spaces

builder/src/Gren/Outline.hs
=> Make sourcemap generation work for submodules on Windows

CONTRIBUTING.md, README.md, ROADMAP.md, devbox.json, devbox.lock, package-lock.json, package.json
The markdown-based documentation is out of date. This is an attempt to update it.
=> Update documentation for how to build compiler

src/Main.gren, src/Terminal/Parser.gren, src/Terminal/Run.gren
Some TODOs we can discuss here but it's working.
=> support `gren run --package`

compiler/src/Generate/JavaScript/Functions.hs
This improves deadd-code elimination when compiled code is post-processed by vite/rollup.
Fixes #324
=> Add NO_SIDE_EFFECT annotation above F[2-9] and A[2-9] functions

builder/src/Reporting.hs
Didn't wait in success case, which meant we didn't always finish telling the user the compilation status.
Fixes #304
=> `attemptWithStyle` didn't always wait for reporting to terminal to finish

gren.json, terminal/Package/Validate.hs
=> Fix crash when running gren package validate.

index.js
=> compileProject in index.js now accepts the optimize flag, as well as multiple entry points.

builder/src/Reporting/Exit.hs, compiler/src/Reporting/Error/Canonicalize.hs, compiler/src/Reporting/Error/Docs.hs, compiler/src/Reporting/Error/Syntax.hs, hints/comparing-records.md, hints/imports.md, hints/init.md, hints/missing-patterns.md, src/Terminal/Parser.gren
=> Fix broken links and some cases of an Gren => a Gren.

src/Terminal/Run.gren
Fixes https://github.com/gren-lang/compiler/issues/316
=> Put `gren run` output under `.gren` dir

src/Terminal/PackageInstall.gren
Fixes #343 
Will aim for a better fix when upgrading the compiler to 25s
=> Filter out invalid module names from project source files.
